config/routes.rb
NsaSnowden::Application.routes.draw do
  root :to => 'sightings#index'
  resources :sightings, only: [:show]
end
 

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  attr_accessible :image, :latitude, :location, :longitude, :remote_image_url

  mount_uploader :image, SightingPicUploader

  geocoded_by :location
  before_save :geocode
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def index
  	@sighting = Sighting.all
  end

  def show
  	@sighting = Sighting.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NsaSnowden
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE']}&sensor=false"
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/sightings/index.html.haml
%h1
	Where's Edward?

= image_tag 'edward.jpg'

%table
	%thead
		%tr
			%th
				Sighting ID
			%th
				Location
			%th
				Latitude
			%th
				Longitude
	%tbody
	-@sighting.each do |sighting|
		%tr
			%td
				=sighting.id
			%td
				=link_to sighting.location, sighting_path(sighting)
			%td
				=sighting.longitude
			%td
				=sighting.latitude
		

app/views/sightings/show.html.haml
%h1
	Sighting# #{@sighting.id} :

= image_tag @sighting.image.large
= image_tag @sighting.image.medium
= image_tag @sighting.image.thumb

#map-canvas

:javascript
	snowden_map.display_map(#{@sighting.latitude},#{@sighting.longitude})
	snowden_map.add_marker(#{@sighting.latitude},#{@sighting.longitude})